name: pytmd-docs
channels:
  - conda-forge
dependencies:
  - docutils<0.18
  - gdal
  - graphviz
  - h5py
  - lxml
  - netCDF4
  - notebook
  - numpy
  - numpydoc
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - pyyaml
  - recommonmark
  - scipy
  - setuptools_scm
  - sphinx
  - sphinx-markdown-tables
  - sphinx_rtd_theme
  - pip:
    - ..
